### PR TITLE
Label and question organization added, behavior questions filled, and T-JS-49 wording adjusted.

### PR DESCRIPTION
**Pull request by EvShaw**
- Added a label and number to each question: 

-  Behavior: B1 through B22
- Technical HTML: T-HTML-1 through T-HTML-11
- Technical CSS: T-CSS-1 through T-CSS-31
- Technical JSS: T-JS-1 through T-JS-54
- Technical JSS: T-JSGeneral-1 through T-JSGeneral-6
- Technical JSS: T-Node-1 through T-Node-27
- Technical CS Theory: T-CSTheory-1 through T-CSTheory-21

-Filled in empty answers for behavior questions: B5, B6, B7, B8, B10, B11, B12, B16, B17, B18, B19, and B21. Worth noting that some of these answers are not in CAR format. 

- Slight adjustment to the wording on the explanation for question: T-JS-49 (Technical JavaScript number49).

### CODE REVIEW

**Comment by curtisbarnard** [comment]
@EvShaw Thanks for the contribution. Can you do me a favor and split this into two PR? Split one as all the number updates which are good. Split the behavioral into a separate PR. You should be able to create a branch off your current branch to accomplish this. Let me know if you need help and I can jump on a call to explain.

**Review by curtisbarnard — CHANGES_REQUESTED** [review]
Split into two PR's: 1) Add numbering and 2) Question answers

**Comment by EvShaw** [comment]
I split them and pushed them as two PRs, in their own branches. I will be available all day tomorrow, please advise if I should have done it differently. Thanks, Curtis.

**Review by curtisbarnard — APPROVED** [review]
Looks good. In the future I would try to keep PR's to 200 lines of code or less as it make review faster and the approvals will go faster.

**Pull request merged**
