### PR TITLE
 answered if one has any Qs for the company, from line 136, fixed typos

### PR DESCRIPTION
**Pull request by tauqeer1040**
- It's my first PR, thanks for this guys
- I answered a  non-technical question. Feel free to edit it out if you have a better answer.
- SUMMARY
- [x] Do you have any questions?
  - What would you like me to accomplish for the company in six months, and a year? How much value do you think is reasonable for me to provide in six months? (Best you get their answer in writing. Atleast make a note.)
  - How flexible is your work-life balance?
  - Any Benefits and mentorship programs this company offers I should be aware of?
  - How did the company take care of its staff during the Covid pandemic?

### CODE REVIEW

**Comment by curtisbarnard** [comment]
@FreelancingTwin I think these are good questions. Maybe they should be split (before you receive an offer and after you receive an offer). I think the first questions would be good in the interview, but the other three would be good after you have an offer.

**Review by curtisbarnard — CHANGES_REQUESTED** [review]
Split the questions into two categories (interview and once you receive the offer)

**Comment by kbventures** [comment]
I would make adjustments to the following: 
"What would you like me to accomplish for the company in the 3months, six months, and a year? How much value do you think is reasonable for me to provide in six months? (Best you get their answer in writing. At least make a note.)"

Most companies decide if they keep you within the first three months. 

I would replace "How did the company take care of its staff during the Covid pandemic?" with

"What does your onboarding process look like?"

Because again, they usually decide within that time period if they keep you!

FInally, I would add this link:

https://www.thebalancecareers.com/questions-to-ask-in-a-job-interview-2061205

As it contains a lot of useful interview questions you can ask an employer and it delves into what you shouldn't ask!

**Comment by tauqeer1040** [comment]
Hey Jason, thanks for the suggestions, glad to do.
Am I to close this PR and request an updated PR?

**Comment by curtisbarnard** [comment]
@FreelancingTwin I believe you can just update your branch with new commits and then the PR will update. No need to open a new one. Just let me know when you are ready for me to review it again. 👍

**Pull request closed without merging**
